---
- hosts: cilium-cluster
  gather_facts: false
  become: yes

  vars_files:
    - envanswer.yml

  tasks:
  - name: Configure BPF mount for Cilium CNI
    copy:
      src: files/sys-fs-bpf.mount
      dest: /etc/systemd/system/sys-fs-bpf.mount
      owner: root
      group: root
      mode: '0644'

  - name: Enable and start sys-fs-bpf.mount service
    systemd:
      name: sys-fs-bpf.mount
      enabled: yes
      state: restarted

  - name: Create /var/run/cilium directory
    file:
      path: /var/run/cilium
      state: directory
      mode: u=rwX,g=rX,o=rX
      recurse: yes

  - name: Create UNIX file socket for Hubble
    file:
      path: /var/run/cilium/hubble.sock
      state: touch
      owner: root
      group: root
      mode: '0664'
