---
- hosts: openshift-haproxy
  become: yes
  gather_facts: false

  vars_files:
    - envanswer.yml

  tasks:
  - name: Install HAProxy
    apt:
      name: ['haproxy']
      force_apt_get: yes
      state: present

  - name: Add repo for HAProxy
    command: add-apt-repository -y ppa:vbernat/haproxy-2.1 --yes
    register: haproxy_apt_repo

  - name: Update repo for HAProxy
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Copy haproxy.cfg file for api-server
    copy:
      src: files/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0644'

  - name: Enable and start HAProxy service
    systemd:
      name: haproxy
      enabled: yes
      state: restarted
