---
- hosts: cilium-cluster
  become: yes
  gather_facts: false

  tasks:
  - name: Install pre-requisite packages
    apt:
      name: ['apt-transport-https', 'gnupg', 'ca-certificates', 'curl', 'software-properties-common', 'inetutils-traceroute']
      force_apt_get: yes
      state: present

  - name: Get Docker GPG key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"

  - name: Add Docker repo
    lineinfile:
      dest: /etc/apt/sources.list.d/docker.list
      line: "deb https://download.docker.com/linux/ubuntu bionic stable"
      create: yes

  - name: Update repo for Docker
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Install Docker
    apt:
      name: ['docker-ce']
      force_apt_get: yes
      state: present

  # Configure Docker properly
  - name: Add deploy user to Docker group
    user:
      name: deploy
      groups: docker
      append: yes

  - name: Enable and start Docker service
    systemd:
      name: docker
      enabled: yes
      state: restarted

  # Install Kubernetes packages
  - name: Install Kubernetes repo key
    shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"

  - name: Create sources.list file for Kubernetes
    lineinfile:
      dest: /etc/apt/sources.list.d/kubernetes.list
      line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      create: yes

  # Apt hash sum mismatch errors continue to plague reliability of playbook to complete
  - name: Clean cache repo before updating
    apt:
      autoclean: yes

  - name: Cleaning /var/lib/apt/lists
    shell: |
       rm -rf /var/lib/apt/lists/*

  - name: Update package cache in Ubuntu
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Install Kubernetes v1.19.3 packages
    apt:
      name: ['kubeadm=1.21.1-00', 'kubectl=1.21.1-00', 'kubelet=1.21.1-00', 'kubernetes-cni']
      force_apt_get: yes
      state: present

  - name: Mark Kubernetes packages to not be upgraded
    shell: "apt-mark hold kubeadm kubectl kubelet kubernetes-cni"


  # Clean-up
  - name: Auto-clean packages
    apt:
      autoclean: yes 
