---
- hosts: cilium-cluster
  become: yes
  gather_facts: false

  tasks:
  # Workaround for hash sum mismatch errors
  - name: Acquire::By-Hash for apt
    lineinfile:
      dest: /etc/apt/apt.conf.d/99acquire-hash
      line: "Acquire::By-Hash \"yes\";"
      create: yes

  - name: Acquire::CompressionTypes for apt
    lineinfile:
      dest: /etc/apt/apt.conf.d/99acquire-compression
      line: "Acquire::CompressionTypes::Order:: \"gz\";"
      create: yes
     
  - name: Auto-clean repo packages
    apt:
      autoclean: yes

  - name: 
    shell: |
      rm -rf /var/lib/apt/lists/*

  - name: Update package cache in Ubuntu
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Update Ubuntu distribution
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Auto-remove unnecessary packages
    apt:
      autoremove: yes
