- hosts: kube_server
  become: false
  remote_user: cris

  # vars_files:
  #   - ansible-vars.yaml
    
  tasks:
  - name: Fetch the file from the master to ansible
    # run_once: yes
    fetch: src=$HOME/.kube/config dest=temp/ flat=yes
    when: "ansible_hostname == 'kube_server'"
  - name: get master kubeconfig to local
    copy: src=temp/config dest=/Users/cris/work/ops/boilerplates/ansible/deploy-k8s-cluster/ws02-config
      # dest: $HOME/.kube/config/{{ cluster_name }}-config
    when: "ansible_hostname == 'local'"
