---
- name: Add specified repository into source list
  # hosts: debian
  hosts: all
  become: True
  tasks:
  - name: Ensure dependencies are installed.
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - vim
        - software-properties-common
      state: present

  - name: Add Kubernetes apt key.
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    register: add_repository_key
    ignore_errors: "{{ kubernetes_apt_ignore_key_error }}"

  - name: Add Kubernetes repository.
    apt_repository:
      repo: "{{ kubernetes_apt_repository }}"
      state: present
      update_cache: true

  - name: Add Kubernetes apt preferences file to pin a version.
    template:
      src: apt-preferences-kubernetes.j2
      dest: /etc/apt/preferences.d/kubernetes
      mode: 0644

  - name: add tuna source 1
    apt_repository:
      repo: deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free
      state: present
  - name: add tuna source 2
    apt_repository:
      repo: deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free
      state: present
  - name: add tuna source 3
    apt_repository:
      repo: deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free
      state: present
  - name: add tuna source 4
    apt_repository:
      repo: deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free
      state: present

  - name: Run apt-get update only
    apt:
      update_cache: True

#- name: Add specified repository into sources list
#  ansible.builtin.apt_repository:
#    repo: deb http://archive.canonical.com/ubuntu hardy partner
#    state: present

#- name: Add specified repository into sources list using specified filename
#  ansible.builtin.apt_repository:
#    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
#    state: present
#    filename: google-chrome

#- name: Add source repository into sources list
#  ansible.builtin.apt_repository:
#    repo: deb-src http://archive.canonical.com/ubuntu hardy partner
#    state: present

#- name: Remove specified repository from sources list
#  ansible.builtin.apt_repository:
#    repo: deb http://archive.canonical.com/ubuntu hardy partner
#    state: absent

#- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
#  ansible.builtin.apt_repository:
#    repo: ppa:nginx/stable

#- name: Add nginx stable repository from PPA and install its signing key on Debian target
#  ansible.builtin.apt_repository:
#    repo: 'ppa:nginx/stable'
#    codename: trusty
