---
- name: Ubuntu install packages Playbook
  hosts: debian
  become: true
  vars:
    - packages:
      # basic
      - wget
      - curl
      #- jq
      #- yarn
      #- openssl
      #- rsync
      ## languages
      #- python3
      #- lua
      #- ruby
      ## shell
      #- zsh
      #- neofetch
      #- exa
      #- broot
      #- starship
      #- git
      #- vim
      #- tmux
      ## DevOps
      #- kubectl
  tasks:
  - name: Update and install package
    package:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install Packages
    package:
      pkg: "{{ packages }}"
      state: latest
      update_cache: yes

#    - name: Apache Service Start
#      service:
#        name: nginx
#        state: restarted
#        enabled: yes