---
- name: Ubuntu copy files Playbook
  hosts: all
  tasks:
  - name: copy files to ubt
    copy:
      src: ./files/k8s_hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: u=rw,g=r,o=r
      backup: yes
    
  - name: copy .bashrc to dest
    copy:
      src: '{{  item.src  }}'
      dest: '{{  item.dest  }}'
      backup: yes
    with_items:
      - {  src: './files/.bashrc',dest: '~/.bashrc'  }