---
- name: ensure ssh-key is present
  hosts: all
  become: true
  tasks:

  - name: Copy ipvs.conf to servers
    copy:
      src: ./files/k8s.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    register: result
  
  - shell: sysctl -p --system
    become: true
    when: result.changed

  
  # - name: sysctl k8s.conf
  #   sysctl:
  #     name: system
  #     state: present
  #     sysctl_file: /etc/sysctl.d/k8s.conf