---
apiVersion: v1
kind: Namespace
metadata:
  name: test-it
# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: test-pool
#   namespace: metallb-system 
# spec:
#   addresses:
#   - 10.0.9.76-10.0.9.82
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: test-layer2
#   namespace: metallb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-it
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-it
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  # externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 10.0.9.181

