---
- name: Set authorized key and change the sshd_config
  hosts: all
  tasks:
    - name: send the pub_keys to remote hosts
      ansible.posix.authorized_key:
        user: "{{ created_username }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      vars:
        created_username: cris

    #- name: Disable password authentication for root
    #  lineinfile:
    #    path: /etc/ssh/sshd_config
    #    state: present
    #    regexp: '^#?PermitRootLogin'
    #    line: 'PermitRootLogin prohibit-password'
