---
- hosts: all
  become: true

  tasks:

  - name: Install ntpdate
    package:
      name: ntpdate
      state: latest

  - name: Set timezone to Asia/Shanghai
    community.general.timezone:
      name: Asia/Shanghai

  - copy:
      src: files/cron.ntpdate
      dest: /etc/cron.d/cron.ntpdate
      #owner: root
      owner: cris
      #group: root
      group: cris
      mode: 0644
