# -*- mode: ruby -*-
# vi: set ft=ruby :

host_list = [
  {
    :name => "vcentos1",
    :box => "centos/7"
  },
  {
    :name => "vcentos2",
    :box => "centos/7"
  },
  {
    :name => "vcentos3",
    :box => "generic/centos8"
  }
]

Vagrant.configure("2") do |config|
  
  # 全局变量
  # config.vm.box = "generic/ubuntu2004"
  # config.vm.network :public_network,
  #     :dev => "virbr0",
  #     :mode => "bridge",
  #     :type => "bridge"
  # 
  # config.vm.synced_folder ".", "/vagrant_data", disabled: true
  # 
  # config.vm.provider :libvirt do |libvirt|
  #   libvirt.cpus = 2
  #   libvirt.memory = 4096
  #   libvirt.nested = true
  # end

  host_list.each do |item|
    config.vm.define host[:name] do |host|
      host.vm.box = item[:box]
      # host.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    end
  end

end
