docker_version: "18.09.0"
rancher_container_name: "rancher-server"
rancher_domain_name: 
rancher_url: "https://rancher.com"
rancher_admin_password: "03220123"
rancher_cluster_name: "cluster_name"
rancher_network_provider: "calico"
install_rook: true
rook_version: "0.9.1"
install_certmanager: true
cluster_issuer_name: "letsencrypt-staging"
letsencrypt_email: "youremail@email.fr"
validate_certs: true
rancher_ssl_port: 443
single_node: false