apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      gzip on;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

      server {
        listen 80;
        
        # 默认路由 - 返回欢迎信息
        location / {
          return 200 "Welcome to Nginx on K3s!";
        }

        # 静态文件路由 - 用于测试静态资源的托管
        location /static/ {
          alias /usr/share/nginx/html/static/;
          autoindex on;  # 启用目录浏览，方便调试
          expires 30d;
          add_header Cache-Control "public, max-age=2592000";
        }

        # 健康检查 - 检查 Nginx 服务是否运行
        location /health {
          return 200 "OK - Nginx is running!";
        }

        # 安全头
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        # 日志配置 - 记录访问和错误日志，方便调试
        error_log /var/log/nginx/error.log warn;
        access_log /var/log/nginx/access.log;
      }
    }
